
CONTIKI_TARGET_SOURCEFILES+=

PLATFORMAPPS+=ip64

include $(CONTIKI)/platform/native/Makefile.native

CFLAGS += -I$(MIST)/platform/mist-native
CFLAGS += -I$(CONTIKI)/platform/native


vpath %.c $(MIST)/platform/mist-native/ $(CONTIKI)/platform/native/ $(CONTIKI)/platform/native/dev


