
CONTIKI_TARGET_SOURCEFILES+=cc2420.c cc2420-arch.c slip_uart1.c

include $(MIST)/platform/mist-exp5438/Makefile.mist-exp5438


contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}
#	$(AR) rcf $@ $^

vpath %.c $(MIST)/platform/mist-exp5438
CFLAGS += -I $(MIST)/platform/mist-exp5438
